$('.new-climb-link').hide()
$('#reset').hide()
newClimbForm = $("<%= j render 'form', climb: @climb %>")
newClimbForm.hide()
$('form#new_climb').remove()
$('#current_section').append(newClimbForm)
newClimbForm.slideDown()
